### ISSUE TITLE
"make tests" fails to build PyEvalUTest

### ISSUE THREAD

**Issue by rekado** [opencog/cogserver#24] opened 2020-01-03 21:09 UTC
I'm packaging cogserver for GNU Guix and found that `make tests` fails to build PyEvalUTest.  Note that I'm building in an environment that only contains Python, but not Cython.

It seems to me that the tests for Python functionality ought to be disabled when the Python bindings have not been built.

Here's the tail of the build log:

~~~
[ 88%] Building CXX object tests/cython/CMakeFiles/PyEvalUTest.dir/PyEvalUTest.cpp.o
cd /tmp/guix-build-cogserver-0-1.c8ad85f.drv-0/build/tests/cython && /gnu/store/x3jx25cd3q363mr7nbgzrhrv1vza6cf7-gcc-7.4.0/bin/c++  -DCONFDIR=\"/gnu/store/16c6l18g5yilphb1rnyc3nwijf1azf6w-cogserver-0-1.c8ad85f/etc\" -DDATADIR=\"/gnu/store/16c6l18g5yilphb1rnyc3nwijf1azf6w-cogserver-0-1.c8ad85f/share/opencog\" -DGUILE_SITE_DIR=\"/gnu/store/16c6l18g5yilphb1rnyc3nwijf1azf6w-cogserver-0-1.c8ad85f/share/guile/site/2.2/\" -DHAVE_ATOMSPACE -DHAVE_COGUTIL -DHAVE_GUILE -DHAVE_GUILE2 -DHAVE_GUILE_2_2 -DPROJECT_BINARY_DIR=\"/tmp/guix-build-cogserver-0-1.c8ad85f.drv-0/build\" -DPROJECT_SOURCE_DIR=\"/tmp/guix-build-cogserver-0-1.c8ad85f.drv-0/source\" -I/gnu/store/1mkkv2caiqbdbbd256c4dirfi4kwsacv-guile-2.2.6/include/guile/2.2 -I/tmp/guix-build-cogserver-0-1.c8ad85f.drv-0/source -I/gnu/store/f5g4av3mwn7zr81yqr1gn9hpb5d2c4m4-boost-1.70.0/include -I/gnu/store/ifsrj0bbpvq3rayq86nr778y3f50li0n-cogutil-2.0.3-1.b07b41b/include -I/gnu/store/d4mbj5yqszdg9rxf6h12jyvyn0hgx3m5-atomspace-5.0.3-1.ed1d316/include -I/tmp/guix-build-cogserver-0-1.c8ad85f.drv-0/build -I/gnu/store/x5fj048bvqpafb07dpidy36fj7l3qfnx-python-minimal-3.7.4/include/python3.7m -I/tmp/guix-build-cogserver-0-1.c8ad85f.drv-0/source/tests/cython  -Wall -fPIC -Wno-variadic-macros -fopenmp -std=gnu++11 -O2 -g -DNDEBUG   -o CMakeFiles/PyEvalUTest.dir/PyEvalUTest.cpp.o -c /tmp/guix-build-cogserver-0-1.c8ad85f.drv-0/build/tests/cython/PyEvalUTest.cpp
In file included from /tmp/guix-build-cogserver-0-1.c8ad85f.drv-0/build/tests/cython/../../../source/tests/cython/PyEvalUTest.cxxtest:6:0,
                 from /tmp/guix-build-cogserver-0-1.c8ad85f.drv-0/build/tests/cython/PyEvalUTest.cpp:24:
/tmp/guix-build-cogserver-0-1.c8ad85f.drv-0/source/opencog/cogserver/modules/python/PyMindAgent.h:13:10: fatal error: opencog/cython/PyIncludeWrapper.h: No such file or directory
 #include <opencog/cython/PyIncludeWrapper.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [tests/cython/CMakeFiles/PyEvalUTest.dir/build.make:70: tests/cython/CMakeFiles/PyEvalUTest.dir/PyEvalUTest.cpp.o] Error 1
make[3]: Leaving directory '/tmp/guix-build-cogserver-0-1.c8ad85f.drv-0/build'
make[2]: *** [CMakeFiles/Makefile2:856: tests/cython/CMakeFiles/PyEvalUTest.dir/all] Error 2
make[2]: Leaving directory '/tmp/guix-build-cogserver-0-1.c8ad85f.drv-0/build'
make[1]: *** [CMakeFiles/Makefile2:129: CMakeFiles/tests.dir/rule] Error 2
make[1]: Leaving directory '/tmp/guix-build-cogserver-0-1.c8ad85f.drv-0/build'
make: *** [Makefile:202: tests] Error 2

Test suite failed, dumping logs.
command "make" "tests" failed with status 2
~~~

**Comment by linas** [comment] 2020-01-04 17:52
Also @noskill this is stuff you know best ...

**Comment by noskill** [comment] 2020-01-20 07:25
cogserver seems to be abandoned, does anyone use it?

**Comment by linas** [comment] 2020-01-20 22:19
I use cogserver all the time. It's a great way of getting a second, third, etc. terminal into a long-running job.  So, for example, in one terminal, you launch some job that runs for hours or days (or weeks, yeah I do that) and in another, you can poke at mem usage stats. look at the atomspace, run other minor/short jobs, etc.  Its great.

Yeah, guile has a network shell to, but it sucks its slow and it's crashy.  Back in the day, python didn't have a network shell, but maybe it does, now? (so if you personally run a python job for a few hours/days, how do you keep tabs on what it's doing? How do you access the atomspace?)

Oh, and there is a different use case, entirely: pump atoms from ROS and other sources, into the atomspace, example, short little messages that update 3D positions of things, etc.  Just a half-dozen atoms every 30 milliseconds or whatever.  cogserver is perfect for that.

So, no, not abandoned at all.

**Comment by rekado** [comment] 2020-01-20 22:41
> Yeah, guile has a network shell to, but it sucks its slow and it's crashy.

Really? Do you mean `guile --listen` or something fancy?  Do you have numbers on its lack of speed?  (I'd also like to see how it is crashy; do you happen to remember bug reports?)

**Comment by linas** [comment] 2020-01-21 01:45
Hi @rekado -- long reply, because I hope you will find it useful.

>>   Yeah, guile has a network shell to, but it sucks its slow and it's crashy.
>
> Really? Do you mean guile --listen or something fancy? Do you have numbers on its lack of speed? (I'd also like to see how it is crashy; do you happen to remember bug reports?)

I'm referring to this page:  https://www.gnu.org/software/guile/manual/html_node/REPL-Servers.html so `(use-modules (system repl server))` and needed setup.

* I have not tried it in guile-3.0, last time I tried was in guile-2.2  (I think, not sure)

* I'm vaguely aware of `guile --listen` but assumed it was a thin wrapper around `(use-modules (system repl server))` and so I never used it much.

* Speed: the use case was to pipe megabytes of scheme code into it every second or two. The message sizes were highly variable: they were parses of English sentences, expressed as scheme, and depending on the sentence, parse ambiguity, parse combinatorial explosion, the messages could vary from a few hundred parenthesis (so a few KBytes of scheme) to maybe a million (so 10-20 MBytes of scheme, as a utf-8 string).  The message rate was basically as fast as the parser could generate, and as fast as the atomspace receive (parsing project gutenberg books). It was instantly apparent that the `system repl server` was 10x or 100x slower than the cogserver; it even seemed to hang or something; I was not motivated to explore.  There was also a second, unrelated issue: the Boehm GC was unhappy doing GC on10MB or 100MB strings, and would print warnings from time to time. So we eventually abandoned this type of i/o, even for the cogserver. (well, relex still needs it, but relex is now abandonware.)

* Crashiness: I've wanted to get rid of the cogserver for many many years. So, for a while, I tried to use the system repl server exclusively. But with compute jobs that run a day or two ... any crash is painful .... so I launch a job in the morning, go eat lunch, fiddle a bit in the afternoon, and have the job crash, ouch. That's effectively a whole-day delay in analyzing results.  Running large jobs is like "watching paint dry" or doing your laundry. Very not fun.  It only took 2 or 3 such incidents to discourage me.  I may have grumbled on either guile-user or guile-devel, but maybe not. I probably didn't bother with a bug report; it seemed absurd to file a report that says "set up this hypercomplex environment, run it for three hours, and use the shell and maybe it will crash and maybe it won't, no single reproducible cause".  Non-reproducibility implies a race condition... Race conditions are tedious to isolate and debug.

There is one bug I do have open, but it's unrelated to the network server (probably?).  I never circled back to, to provide a small, simple test case, but -- it is (was) very reproducible in my complex environment. The bug: if you feed guile large s-expression strings, in the 500KByte to 20MByte range, and feed those strings to `eval`, then something somewhere will corrupt and crash ... after half an hour... i.e. after hundreds (or more) of these kinds of strings.  I was making some progress on creating a small test case for this, as it was "easily" reproducible (for me), but very hard to cut it down to a size that can be submitted ... that's a lot of work.  I spent a few days debugging; the crashes were always deep inside the JIT compiler, for guile-2.9.1 or 2.9.2. It was a race - it would always crash, usually/always in the same place, but never for the same input data. Intermittent.  It's possible that it's been fixed in guile-3.0; but it's painful to reproduce, and so I simply stopped handllng data in this way, and switched to a different style.

I mention this because you mentioned that one should  "read s-expressions", and my experience was that there's a bug in that code path, but it required such a complex environment to reproduce that I could not pin down the blame.

**Comment by linas** [comment] 2020-01-21 01:59
I should mention that the cogserver allows you to have a guile shell AND a python shell, at the same time, into the same atomspace. That alone makes it more-or-less irreplacable.

**Comment by linas** [comment] 2020-01-21 16:48
@rekado one last note: The `ShellUTest` opens a dozen network connections to the cogserver, then blasts s-exprs at it, through each. It should be easy (trivial?) to aim it at the guile network server instead, and see what happens.

**Comment by linas** [comment] 2020-02-29 21:46
Closing; I think this is fixed ... yesterday, I got this:
```
    Start 1: AgentModuleUTest
1/6 Test #1: AgentModuleUTest .................   Passed    0.73 sec
    Start 2: AgentUTest
2/6 Test #2: AgentUTest .......................   Passed    0.12 sec
    Start 3: PythonModuleUTest
3/6 Test #3: PythonModuleUTest ................   Passed    0.56 sec
    Start 4: PyEvalUTest
4/6 Test #4: PyEvalUTest ......................   Passed    0.19 sec
    Start 5: CythonServer
5/6 Test #5: CythonServer .....................   Passed    0.50 sec
    Start 6: ShellUTest
6/6 Test #6: ShellUTest .......................   Passed  182.87 sec

100% tests passed, 0 tests failed out of 6
```

so either it works, or there is some other bug and it "works for me but not for you". If its the later, please open a new issue!? (This one is already clogged up with conversation).

**Closed by linas** 2020-02-29 21:46 UTC

**Comment by linas** [comment] 2020-02-29 21:49
Also `opencog/CMakeLists.txt` now says:
```
IF(HAVE_CYTHON)
   ADD_SUBDIRECTORY (cython)
ENDIF(HAVE_CYTHON)
```

so there should not be any attempt to build the python cogserver, if python is not installed. (I have not directly tested...)
